#**Espacios Vectoriales**

Un espacio vectorial se define como un conjunto V junto con dos operaciones: suma de vectores y multiplicación por un escalar. Para que V sea un espacio vectorial, estas operaciones deben cumplir ciertas propiedades algebraicas. Ejemplos de espacios vectoriales incluyen el espacio R^n de n-tuplas de números reales, el espacio de funciones continuas y el espacio de matrices.

Es útil comprender esta definición a través de ejemplos concretos. Ejemplos comunes de espacios vectoriales:

Espacio R^n: El espacio R^n representa todas las n-tuplas de números reales. Por ejemplo, en R^2, los vectores serían parejas ordenadas de números reales (x, y), donde x e y pueden tomar cualquier valor real. La suma vectorial se realiza componente por componente, y la multiplicación por un escalar se aplica a cada componente individualmente.

Espacio de matrices: El espacio de matrices, como el conjunto de todas las matrices de tamaño m x n, forma un espacio vectorial. La suma de matrices se realiza sumando las entradas correspondientes, y la multiplicación por un escalar implica multiplicar cada entrada por ese escalar.

Espacio de polinomios: El conjunto de todos los polinomios de grado n o menor forma un espacio vectorial.

Espacio de funciones: Puede ser un espacio vectorial. Por ejemplo, el conjunto de todas las funciones continuas en un intervalo dado forma un espacio vectorial.

Espacio de vectores polares: Los vectores en un plano polar, definidos por un ángulo y una distancia del origen, forman un espacio vectorial. La suma de vectores polares se realiza combinando las distancias y sumando los ángulos, y la multiplicación por un escalar afecta solo a la distancia.

**Subespacios vectoriales**

Un subespacio vectorial es un conjunto que es un espacio vectorial en sí mismo. Para que un subconjunto de un espacio vectorial sea un subespacio vectorial, debe cumplir ciertas propiedades, como contener el vector cero, ser cerrado bajo la suma de vectores y la multiplicación por un escalar

**Subespacios generadores**

Un subespacio generador es un subconjunto de un espacio vectorial que genera todo el espacio mediante combinaciones lineales de sus elementos.

**Combinación lineal: Dependencia e independicia lineal**

Una combinación lineal de vectores es una expresión en la que se multiplican los vectores por escalares y se suman los resultados. Si un vector puede ser expresado como una combinación lineal de otros vectores, se dice que es dependiente de esos vectores. Si un conjunto de vectores no tiene ninguna combinación lineal que los iguale a cero, se dice que son linealmente independientes. La dependencia e independencia lineal de vectores están relacionadas con la existencia de soluciones únicas en sistemas de ecuaciones lineales.

**Base y dimensión**

Una base de un espacio vectorial es un conjunto de vectores linealmente independientes que generan todo el espacio. Cualquier vector del espacio puede ser expresado de manera única como una combinación lineal de los vectores de la base. La dimensión de un espacio vectorial es el número de vectores en cualquier base del espacio. La dimensión de un espacio vectorial finito-dimensional es igual al número de elementos en su base.

**Coordenadas y matriz cambio de base**

Las coordenadas de un vector en relación a una base son los coeficientes de la combinación lineal de los vectores de la base necesarios para representar ese vector. La matriz cambio de base es una matriz que permite convertir las coordenadas de un vector en relación a una base a las coordenadas del mismo vector en relación a otra base. Esta matriz se obtiene concatenando las columnas que representan las coordenadas de los vectores de la base de destino expresadas en la base de origen.

**Bases Ortogonales y ortonormales**

Bases Ortogonales:
Una base ortogonal es un conjunto de vectores en el cual cada par de vectores es ortogonal, lo que significa que el producto escalar entre ellos es igual a cero. Esto implica que los vectores en la base son perpendiculares entre sí. En una base ortogonal, no hay dependencia lineal entre los vectores, lo que facilita el cálculo de proyecciones y descomposiciones.

Bases Ortonormales:
Una base ortonormal es una base ortogonal en la cual todos los vectores tienen una longitud o norma igual a 1. Además de ser perpendiculares entre sí, los vectores en una base ortonormal también están normalizados. Esto significa que cada vector se divide por su longitud para que tenga una norma de 1. Una base ortonormal simplifica aún más los cálculos y permite una interpretación geométrica clara.

La principal diferencia entre una base ortogonal y una base ortonormal radica en las longitudes de los vectores. Mientras que en una base ortogonal los vectores pueden tener diferentes longitudes, en una base ortonormal todos los vectores tienen una longitud de 1.

Las bases ortogonales y ortonormales son muy utilizadas en diferentes áreas de las matemáticas y la física, especialmente en el álgebra lineal y la geometría.



In [1]:
#Ejercicios 
#Suma y multiplicación por escalar en R^3:
import numpy as np

# Crear vectores en R^3
v1 = np.array([1, 2, 3])
v2 = np.array([-2, 0, 1])

# Suma de vectores
suma = v1 + v2
print("Suma:", suma)

# Multiplicación por escalar
escalar = 3
multiplicacion = escalar * v1
print("Multiplicación por escalar:", multiplicacion)

#Producto punto en R^2:

import numpy as np

# Crear vectores en R^2
v1 = np.array([1, 2])
v2 = np.array([-2, 0])

# Producto punto
producto_punto = np.dot(v1, v2)
print("Producto punto:", producto_punto)


#Verificar independencia lineal en R^4:

# Crear vectores en R^4
v1 = np.array([1, 0, 0, 0])
v2 = np.array([0, 1, 0, 0])
v3 = np.array([0, 0, 1, 0])
v4 = np.array([0, 0, 0, 1])

# Verificar independencia lineal
matriz = np.column_stack((v1, v2, v3, v4))
determinante = np.linalg.det(matriz)
if determinante != 0:
    print("Los vectores son linealmente independientes.")
else:
    print("Los vectores son linealmente dependientes.")

Suma: [-1  2  4]
Multiplicación por escalar: [3 6 9]
Producto punto: -2
Los vectores son linealmente independientes.


In [2]:
#Subespacios vectoriales. Subespacios generadores.
import numpy as np
# Definir un conjunto de vectores en R^3
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
# Comprobar si los vectores generan un subespacio
subespacio = np.array([v1, v2])
es_subespacio = np.linalg.matrix_rank(subespacio) == np.linalg.matrix_rank(subespacio.T)
if es_subespacio:
    print("Los vectores generan un subespacio.")
else:
    print("Los vectores no generan un subespacio.")


#Combinación lineal. Dependencia e Independencia lineal.
# Definir un conjunto de vectores en R^2
v1 = np.array([1, 2])
v2 = np.array([-2, -4])
# Verificar si los vectores son linealmente independientes
matriz = np.column_stack((v1, v2))
determinante = np.linalg.det(matriz)
if determinante != 0:
    print("Los vectores son linealmente independientes.")
else:
    print("Los vectores son linealmente dependientes.")
# Calcular una combinación lineal de los vectores
coeficientes = np.array([2, -1])
combinacion_lineal = coeficientes[0] * v1 + coeficientes[1] * v2
print("Combinación lineal:", combinacion_lineal)


#Base y dimensión.
# Definir un conjunto de vectores en R^3
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
v3 = np.array([0, 0, 1])
# Verificar si los vectores forman una base
matriz = np.column_stack((v1, v2, v3))
es_base = np.linalg.matrix_rank(matriz) == matriz.shape[1]
if es_base:
    print("Los vectores forman una base.")
else:
    print("Los vectores no forman una base.")
# Calcular la dimensión del espacio generado por los vectores
dimension = np.linalg.matrix_rank(matriz)
print("Dimensión:", dimension)


#Coordenadas y Matriz cambio de base.
# Definir una matriz de cambio de base
matriz_cambio = np.array([[1, 2], [3, 4]])
# Definir un vector en la base original
v1 = np.array([1, 1])
# Calcular las coordenadas del vector en la nueva base
coordenadas = np.linalg.inv(matriz_cambio) @ v1
print("Coordenadas:", coordenadas)
# Calcular la matriz cambio de base inversa
matriz_cambio_inversa = np.linalg.inv(matriz_cambio)
print("Matriz cambio de base inversa:", matriz_cambio_inversa)


#Bases Ortogonales y ortonormales.
# Definir un conjunto de vectores en R^3
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
v3 = np.array([0, 0, 1])
# Convertir los vectores en una base ortogonal
u1 = v1
u2 = v2 - np.dot(v2, u1) * u1
u3 = v3 - np.dot(v3, u1) * u1 - np.dot(v3, u2) * u2
base_ortogonal = np.column_stack((u1, u2, u3))
print("Base ortogonal:", base_ortogonal)
# Normalizar los vectores para obtener una base ortonormal
norma_u1 = np.linalg.norm(u1)
norma_u2 = np.linalg.norm(u2)
norma_u3 = np.linalg.norm(u3)
u1_ortonormal = u1 / norma_u1
u2_ortonormal = u2 / norma_u2
u3_ortonormal = u3 / norma_u3
base_ortonormal = np.column_stack((u1_ortonormal, u2_ortonormal, u3_ortonormal))
print("Base ortonormal:", base_ortonormal)

Los vectores generan un subespacio.
Los vectores son linealmente dependientes.
Combinación lineal: [4 8]
Los vectores forman una base.
Dimensión: 3
Coordenadas: [-1.  1.]
Matriz cambio de base inversa: [[-2.   1. ]
 [ 1.5 -0.5]]
Base ortogonal: [[1 0 0]
 [0 1 0]
 [0 0 1]]
Base ortonormal: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
