#**Matrices**


Definición: Una matriz es una estructura rectangular de elementos dispuestos en filas y columnas, utilizada para almacenar y manipular datos numéricos o simbólicos.

Los elementos individuales de una matriz se llaman entradas o elementos de la matriz. Cada entrada se identifica mediante su posición en la matriz, utilizando dos índices: uno para la fila y otro para la columna. Por ejemplo, el elemento en la fila i y columna j se denota como A[i, j].


In [ ]:
import numpy as np
import sympy as sym
A = sym.Matrix ([[0,1,2,-1,1],[1,0,2,0,-1],[1,0,2,0,-1],[1,2,4,-2,3]]) #creando matriz A
print(A)

Matrix([[0, 1, 2, -1, 1], [1, 0, 2, 0, -1], [1, 0, 2, 0, -1], [1, 2, 4, -2, 3]])


##**Tipos de matrices**

Hay varios tipos de matrices en matemáticas, que se clasifican según sus propiedades y estructuras particulares. Aquí tienes algunos de los tipos más comunes de matrices:

**Matriz rectangular**: Una matriz rectangular es aquella en la que el número de filas y columnas es diferente.

**Matriz cuadrada**: Una matriz cuadrada es aquella en la que el número de filas es igual al número de columnas. Por ejemplo, una matriz 3x3 o una matriz 2x2 son matrices cuadradas.

**Matriz nula**: Una matriz nula es aquella en la que todos sus elementos son cero.

**Matriz diagonal**: Una matriz diagonal es aquella en la que todos los elementos fuera de la diagonal principal es 0.

**Matriz triangular cuadrada superior**: es aquella que aij=0, tal que i>j.

**Matriz triangular cuadrada inferior**: es aquella que aij=0, tal que j>i.

**Matriz simétrica**:Una matriz cuadrada tal que A=A^T.

**Matriz antisimétrica**: Una matriz tal que los elementos de su diagonal son 0 y A^T= -A.

**Matriz nilpotente**: Es una matriz cuadrada de orden p tal que A^p=0

**Matriz idemponente**: Es una matriz cuadrada. Si A^2=A, es decir A^n=A.



In [ ]:
#Ejemplos en Codigo 
import numpy as np
import sympy as sym
#Matriz rectangular
A = sym.Matrix ([[0,1,2,-1,1],[1,0,2,0,-1],[1,0,2,0,-1],[1,2,4,-2,3]]) #creando matriz A
print(A)
#Matriz cuadrada
B = sym.Matrix ([[2,1,-3,-1],[1,1,2,7],[-1,0,0,0],[1,0,0,2]]) #creando matriz A
print(B)
#Matriz nula 
C = sym.Matrix ([[0,0,0,0],[0,0,0,0],[0,0,0,0],[0,0,0,0]]) #creando matriz A
print(C)
#Matriz diagonal 
D = sym.Matrix ([[2,0,0,0],[0,1,0,0],[0,0,2,0],[0,0,0,2]]) #creando matriz A
print(D)
#Matriz triangular cuadrada superior
E = sym.Matrix ([[1,5,7,3],[0,2,3,4],[0,0,2,6],[0,0,0,7]]) #creando matriz A
print(E)
#Matriz triangular cuadrada inferior
E = sym.Matrix ([[1,0,0,0],[1,2,0,0],[4,5,2,0],[3,-4,5,0]]) #creando matriz A
print(E)
#Matriz simétrica
def es_simetrica(matriz):
    # Comprobar si la matriz es igual a su traspuesta
    traspuesta = np.transpose(matriz)
    return np.array_equal(matriz, traspuesta)

    # Crear una matriz simétrica
matriz_simetrica = np.array([[1, 2, 3],
                             [2, 4, 5],
                             [3, 5, 6]])

    # Verificar si la matriz es simétrica
if es_simetrica(matriz_simetrica):
    print("La matriz es simétrica.")
else:
    print("La matriz no es simétrica.")
#Matriz antisimétrica

def es_antisimetrica(matriz):
    # Comprobar si la matriz negativa es igual a su traspuesta
    traspuesta = np.transpose(matriz)
    negativa = np.negative(matriz)
    return np.array_equal(negativa, traspuesta)

# Crear una matriz antisimétrica
matriz_antisimetrica = np.array([[0, 2, -3],
                                 [-2, 0, 4],
                                 [3, -4, 0]])

# Verificar si la matriz es antisimétrica
if es_antisimetrica(matriz_antisimetrica):
    print("La matriz es antisimétrica.")
else:
    print("La matriz no es antisimétrica.")
    
#Matriz nilpotente
    # Crear una matriz nilpotente de orden 3
matriz_nilpotente = np.array([[0, 1, 0],
                              [0, 0, 1],
                              [0, 0, 0]])

    # Elevar la matriz al cuadrado
matriz_cuadrado = np.matmul(matriz_nilpotente, matriz_nilpotente)

    # Elevar la matriz al cubo
matriz_cubo = np.matmul(matriz_cuadrado, matriz_nilpotente)

    # Comprobar si la matriz es nilpotente
es_nilpotente = np.array_equal(matriz_cubo, np.zeros((3, 3)))

     # Imprimir la matriz y el resultado de ser nilpotente
print("Matriz nilpotente:")
print(matriz_nilpotente)

if es_nilpotente:
    print("La matriz es nilpotente.")
else:
    print("La matriz no es nilpotente.")
#Matriz idemponente
   # Crear una matriz idempotente
matriz_idempotente = np.array([[1, 0, 0],
                              [0, 1, 0],
                              [0, 0, 0]])

   # Elevar la matriz al cuadrado
matriz_cuadrado = np.matmul(matriz_idempotente, matriz_idempotente)

  # Comprobar si la matriz es idempotente
es_idempotente = np.array_equal(matriz_cuadrado, matriz_idempotente)

  # Imprimir la matriz y el resultado de ser idempotente
print("Matriz idempotente:")
print(matriz_idempotente)

if es_idempotente:
    print("La matriz es idempotente.")
else:
    print("La matriz no es idempotente.")

Matrix([[0, 1, 2, -1, 1], [1, 0, 2, 0, -1], [1, 0, 2, 0, -1], [1, 2, 4, -2, 3]])
Matrix([[2, 1, -3, -1], [1, 1, 2, 7], [-1, 0, 0, 0], [1, 0, 0, 2]])
Matrix([[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]])
Matrix([[2, 0, 0, 0], [0, 1, 0, 0], [0, 0, 2, 0], [0, 0, 0, 2]])
Matrix([[1, 5, 7, 3], [0, 2, 3, 4], [0, 0, 2, 6], [0, 0, 0, 7]])
Matrix([[1, 0, 0, 0], [1, 2, 0, 0], [4, 5, 2, 0], [3, -4, 5, 0]])
La matriz es simétrica.
La matriz es antisimétrica.
Matriz nilpotente:
[[0 1 0]
 [0 0 1]
 [0 0 0]]
La matriz es nilpotente.
Matriz idempotente:
[[1 0 0]
 [0 1 0]
 [0 0 0]]
La matriz es idempotente.


##**Operaciones de matrices**

**Suma y Resta**

Se necesitan que la dos matrices que se desean sumar sean del mismo orden y la matriz resultante de la suma será del mismo orden que las matrices anteriores, tal que Amxn + Bmxn = Cmxn.

**Producto de una matriz por un escalar**

Sea c que pertenece a los reales y A una matriz de orden mxn sobre los reales. 
c * Amxn = Dmxn

**Producto de matrices**

Se A y B matrices sobre los reales, tal que A es de orden mxd y B una mtria de orden dxn, el producto de matrices es:
Amxd * Bdxn = Cmxn

Propiedades de matrices

-A(D*E) = (A*D)*E
-A(C+D) = AC + AD
-(A+B)*C = AC + BC
-A(αC) = α(AC) = (αA)  C

In [ ]:
#Ejemplos
import numpy as np
import sympy as sym
#Suma
A = sym.Matrix ([[0,1,2,-1,1],[1,0,2,0,-1],[1,0,2,0,-1],[1,2,4,-2,3]]) 
print(A)
B = sym.Matrix ([[1,2,2,-3,4],[1,0,2,-6,-1],[1,0,3,5,-1],[1,-2,-5,7,3]]) 
print(B)
C = A + B
print (C)
#Producto escalar por la matriz
D = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

producto = 2 * D
print(producto)
print(" ")
#Producto de matrices
matriz1 = np.array([[1, 2, 3],
                    [4, 5, 6]])

matriz2 = np.array([[7, 8],
                    [9, 10],
                    [11, 12]])
producto = np.dot(matriz1, matriz2)
print(producto)

Matrix([[0, 1, 2, -1, 1], [1, 0, 2, 0, -1], [1, 0, 2, 0, -1], [1, 2, 4, -2, 3]])
Matrix([[1, 2, 2, -3, 4], [1, 0, 2, -6, -1], [1, 0, 3, 5, -1], [1, -2, -5, 7, 3]])
Matrix([[1, 3, 4, -4, 5], [2, 0, 4, -6, -2], [2, 0, 5, 5, -2], [2, 0, -1, 5, 6]])
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
 
[[ 58  64]
 [139 154]]


##**Inversión de matrices**

Sea A una matriz cuadrada que opera sobre los reales; si existe una matriz B cuadrada ta que AB=BA=I. Se dice que  B es la inversa de A y B = A^-1

**Teorema**

Si A es inversible entonces (A^-1)^-1=A

**Teorema 2**
Si A y B son inversibles entonces su producto es inversible: 
(AB)^-1 = B^-1 * A^-1


In [ ]:
import numpy as np

# Definir la matriz
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Calcular la inversa de la matriz
try:
    matriz_inversa = np.linalg.inv(matriz)
    print("Matriz inversa:")
    print(matriz_inversa)
except np.linalg.LinAlgError:
    print("La matriz no tiene inversa.")

La matriz no tiene inversa.


##**Métodos para obtener la inversa de una matriz**

**1. Método Directo (con Matriz Adjunta)**

Paso 1: Dada una matriz cuadrada A de tamaño n x n, se calcula el determinante de la matriz A. Para calcular el determinante se aplica lo siguiente:

Para una matriz de tamaño n x n, donde n es mayor que 2, se aplica la expansión por cofactores.
Selecciona una fila o columna de la matriz y calcula el determinante de cada elemento de esa fila o columna multiplicado por su cofactor correspondiente. El cofactor de un elemento se calcula como (-1)^(i + j) * M(i, j), donde M(i, j) es el determinante de la submatriz obtenida al eliminar la fila i y la columna j de la matriz original.
Suma todos los productos obtenidos para obtener el determinante de la matriz.
Puedes elegir cualquier fila o columna para aplicar la expansión por cofactores.

Paso 2: Si el determinante es igual a cero, entonces la matriz A no tiene inversa.

Paso 3: Si el determinante es diferente de cero, se calcula la matriz adjunta de A, que se obtiene al tomar la matriz de cofactores transpuesta.
Paso 4: Finalmente, se obtiene la inversa multiplicando la matriz adjunta por el inverso del determinante: A^(-1) = (1/det(A)) * adj(A).


**2. Método de Gauss (Matriz Ampliada con la I)**

Paso 1: Dada una matriz aumentada [A | I], se realiza eliminación hacia adelante para convertir la matriz A en la matriz identidad.
Paso 2: Una vez que se obtiene una matriz en forma escalonada reducida, se realiza eliminación hacia atrás para convertir la matriz identidad en la matriz A inversa.
Paso 3: Al finalizar, se obtiene la matriz A^(-1) en el lado derecho de la barra vertical (|) en la matriz aumentada.

In [ ]:
#Metodo para obtener la inversa de una matriz
import numpy as np

# Matriz de ejemplo
A = np.array([[1, 2],
              [3, 4]])

# Método Directo
det_A = np.linalg.det(A)
if det_A == 0:
    print("La matriz A no tiene inversa.")
else:
    adj_A = np.linalg.inv(A).T * det_A
    inverse_direct = adj_A / det_A
    print("Inversa (Método Directo):")
    print(inverse_direct)

#Metodo de Gauss
# Definir la matriz
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Definir la matriz identidad del mismo tamaño
matriz_identidad = np.eye(matriz.shape[0])

# Concatenar la matriz y la matriz identidad
matriz_aumentada = np.hstack((matriz, matriz_identidad))


def gauss_inversa(matriz):
    n = len(matriz)
    identidad = np.eye(n)
    matriz_aumentada = np.concatenate((matriz, identidad), axis=1)

    for i in range(n):
        pivote = matriz_aumentada[i, i]
        if pivote == 0:
            raise ValueError("La matriz no tiene inversa")
        
        matriz_aumentada[i] /= pivote
        
        for j in range(n):
            if i != j:
                factor = matriz_aumentada[j, i]
                matriz_aumentada[j] -= factor * matriz_aumentada[i]

    inversa = matriz_aumentada[:, n:]
    return inversa

# Ejemplo de matriz
matriz = np.array([[1, 2, 3],
                   [0, 1, 4],
                   [5, 6, 0]])

# Obtener la inversa mediante el método de Gauss
inversa = gauss_inversa(matriz)

# Imprimir la inversa
print("Inversa:")
print(inversa)

Inversa (Método Directo):
[[-2.   1.5]
 [ 1.  -0.5]]
Inversa:
[[-24.  18.   5.]
 [ 20. -15.  -4.]
 [ -5.   4.   1.]]


##**Operaciones elementales con fila**

Son 3 operaciones elementales por fila 

1. Multiplicación de un escalar por una fila. 

2. Reemplazar la enésima fila de A por la fila r + c veces la fila S, tal que S !=r.

3. Intercambio de filas. 

Expresado: 

i) e(A)rj = c* Arj

ii) e(A)rj = Arj + cAsj

iii) e(A)rj = Asj

In [ ]:
#Operaciones elementales con fila
#1. Multiplicación de un escalar por una fila
import numpy as np
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
escalar = 2
matriz[1] = matriz[1] * escalar
print("Matriz después de la multiplicación:")
print(matriz)

#2. Reemplazar la enésima fila de A por la fila r + c*Fila s, tal que s != r

matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
escalar = -2
matriz[0] = (matriz[1] * escalar) + matriz[0]
print(" ")
print("Matriz después de la multiplicación:")
print(matriz)

#3. Intercambio de filas 
matriz = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Matriz original:")
print(matriz)
fila1 = 1
fila2 = 2
matriz[[fila1, fila2]] = matriz[[fila2, fila1]]
print("Matriz después del intercambio de filas:")
print(matriz)


Matriz después de la multiplicación:
[[ 1  2  3]
 [ 8 10 12]
 [ 7  8  9]]
 
Matriz después de la multiplicación:
[[-7 -8 -9]
 [ 4  5  6]
 [ 7  8  9]]
Matriz original:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Matriz después del intercambio de filas:
[[1 2 3]
 [7 8 9]
 [4 5 6]]


##**Rango de una matriz**

El rango de una matriz es el mayor de los órdenes de los menores no nulos que podemos encontrar
en la matriz. Por tanto, el rango no puede ser mayor al número de filas o de columnas. También
se define el rango de una matriz como el número máximo de filas o columnas linealmente independientes. esta segunda definición nos va a permitir relacionar el concepto de rango con conceptos
relativos a espacios vectoriales.

In [ ]:
import numpy as np

# Definir la matriz
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Calcular el rango de la matriz
rango = np.linalg.matrix_rank(A)

# Imprimir el rango
print("Rango de la matriz:", rango)

Rango de la matriz: 2
