**Matrices Particionadas**

Las matrices particionadas son matrices grandes que se dividen en bloques más pequeños para facilitar su manipulación y análisis.

Algunas de las propiedades y características de las matrices particionadas son:

1. Operaciones: Las matrices particionadas permiten realizar operaciones matemáticas como suma, resta y multiplicación de matrices, teniendo en cuenta la estructura de bloques. Por ejemplo, la suma de dos matrices particionadas se realiza sumando los bloques correspondientes.

2. Inversa: Si una matriz particionada es invertible, su inversa también puede ser particionada en bloques correspondientes. Es decir, la inversa de una matriz particionada tiene una estructura similar a la matriz original.

3. Submatrices: Las matrices particionadas contienen submatrices más pequeñas como bloques. Estas submatrices pueden ser extraídas o manipuladas de manera individual para realizar cálculos específicos.

4. Resolución de sistemas de ecuaciones: Las matrices particionadas se utilizan en la resolución de sistemas de ecuaciones lineales. Al particionar una matriz de coeficientes, es posible realizar operaciones específicas en cada bloque para simplificar el sistema y encontrar soluciones.

**Vectores y valores Propios**

Los vectores propios son vectores no nulos que, al multiplicarse por una matriz, dan lugar a un múltiplo escalar del mismo vector. Los valores propios son los escalares asociados a los vectores propios.

 Valor propio: Un valor propio (también llamado autovalor) de una matriz cuadrada A es un escalar λ tal que cuando se le aplica A a un vector no nulo x, el resultado es un múltiplo escalar de x, es decir, Ax = λx. En otras palabras, el vector x no cambia de dirección, solo se escala por un factor λ. El valor propio λ puede ser real o complejo.

- Vector propio: Un vector propio (también llamado autovector) corresponde a un valor propio y es un vector no nulo x que satisface la ecuación Ax = λx. El vector propio es importante porque representa la dirección en la cual ocurre el estiramiento o contracción característico de la matriz A.

- Ecuación característica: La ecuación característica es una ecuación matemática que se utiliza para encontrar los valores propios de una matriz. Para una matriz cuadrada A de tamaño n, la ecuación característica se define como det(A - λI) = 0, donde det() es el determinante, λ es el valor propio desconocido y I es la matriz identidad de tamaño n. Resolver esta ecuación proporciona los valores propios λ de la matriz A.

- Polinomio característico: El polinomio característico es una expresión algebraica obtenida a partir de la ecuación característica al expandir el determinante. El polinomio característico se representa como P(λ) = det(A - λI) y es una función polinómica en λ. Las raíces de este polinomio son los valores propios de la matriz A.

**Teorema de Cayley-Hamilton**

El teorema de Cayley-Hamilton establece que toda matriz satisface su propia ecuación característica, lo que implica que puede expresarse como una combinación lineal de sus potencias.

**Diagonzalizacion de matrices**

La diagonalización de una matriz implica descomponerla en una forma especial donde la matriz resultante es diagonal y las columnas de la matriz de transformación son los vectores propios de la matriz original.

Una matriz cuadrada A se puede diagonalizar si cumple con las siguientes condiciones:

1. La matriz debe ser diagonalizable, lo cual implica que debe tener un conjunto completo de vectores propios linealmente independientes.

2. Los vectores propios asociados a cada valor propio deben formar una base del espacio vectorial correspondiente.

El proceso de diagonalización implica los siguientes pasos:

1. Calcular los valores propios de la matriz A resolviendo la ecuación característica: det(A - λI) = 0, donde λ representa el valor propio y I es la matriz identidad.

2. Para cada valor propio, encontrar el vector propio correspondiente resolviendo la ecuación (A - λI)v = 0, donde v es el vector propio.

3. Construir la matriz P utilizando los vectores propios encontrados. Los vectores propios deben ser colocados como columnas de la matriz P.

4. Calcular la matriz diagonal D, donde los valores propios se colocan en la diagonal principal.

In [1]:
#Ejercicios 


# Matrices Particionadas.
import numpy as np

# Definición de la matriz particionada
A = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

# Partición de la matriz en bloques
B = A[:, :2]
C = A[:, 2:]

print("Matriz original:")
print(A)
print("Matriz particionada B:")
print(B)
print("Matriz particionada C:")
print(C)


#Vectores y Valores Propios
# Definición de la matriz
A = np.array([[3, -1],
              [2, 4]])

# Cálculo de los valores y vectores propios
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Valores propios:")
print(eigenvalues)
print("Vectores propios:")
print(eigenvectors)


#Teorema de Cayley-Hamilton.
# Definición de la matriz
A = np.array([[2, 1],
              [4, 3]])
# Cálculo del polinomio característico
polynomial = np.poly(A)
print("Polinomio característico:")
print(polynomial)

#Diagonalización de matrices.
# Definición de la matriz
A = np.array([[2, 1],
              [4, 3]])

# Cálculo de la diagonalización
eigenvalues, eigenvectors = np.linalg.eig(A)
D = np.diag(eigenvalues)
P = eigenvectors

# Matriz diagonalizada
A_diag = np.dot(np.dot(np.linalg.inv(P), A), P)

print("Matriz original:")
print(A)
print("Matriz diagonalizada:")
print(A_diag)

Matriz original:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Matriz particionada B:
[[ 1  2]
 [ 5  6]
 [ 9 10]]
Matriz particionada C:
[[ 3  4]
 [ 7  8]
 [11 12]]
Valores propios:
[3.5+1.32287566j 3.5-1.32287566j]
Vectores propios:
[[-0.20412415+0.54006172j -0.20412415-0.54006172j]
 [ 0.81649658+0.j          0.81649658-0.j        ]]
Polinomio característico:
[ 1. -5.  2.]
Matriz original:
[[2 1]
 [4 3]]
Matriz diagonalizada:
[[ 4.38447187e-01 -1.01048649e-15]
 [ 7.35257583e-17  4.56155281e+00]]
